#!/bin/bash
clear
[[ $(awk -F" " '{print $2}' /usr/lib/nzx) != "@Niltonjuniornzx" ]] && exit 0
sleep 1
clear
echo ""
echo "--------------------------------------------------------------------"
speedtest-cli --share
echo ""

echo "--------------------------------------------------------------------"